#!/bin/sh 
### BEGIN INIT INFO 
# Provides: zram 
# Required-Start: $local_fs 
# Required-Stop: $local_fs 
# Default-Start: S 
# Default-Stop: 0 1 6 
# Short-Description: Use compressed RAM as in-memory swap 
# Description: Use compressed RAM as in-memory swap 
### END INIT INFO 

# Forked by: Dale MM0HGW <dale@piratepress.org>
# rev 1: zramctl as https://askubuntu.com/questions/730749/how-to-change-zram-size
# Author: Antonio Galea <antonio.galea@gmail.com> 
# Thanks to Przemysław Tomczyk for suggesting swapoff parallelization 
# Distributed under the GPL version 3 or above, see terms at 
# https://gnu.org/licenses/gpl-3.0.txt 

FRACTION=75 
MEMORY=`perl -ne'/^MemTotal:\s+(\d+)/ && print $1*1024;' < /proc/meminfo` 
CPUS=`nproc`
THREADS=$(( 1 > CPUS - 1 ? 1 : CPUS - 1 )) 
SIZE=$(( MEMORY * FRACTION / 100 )) 
case "$1" in 
	"start") 
		modprobe zram
		zramctl -f -a lz4 --size $SIZE -t $THREADS /dev/zram0
		mkswap /dev/zram0
		swapon /dev/zram0 -p 100
		;; 
	"stop") 
		swapoff /dev/zram0 
		wait 
		sleep .5 
		modprobe -r zram 
		;; 
	*) 
		echo "Usage: `basename $0` (start | stop)" 
		exit 1 
		;; 
esac
