#!/bin/sh 
### BEGIN INIT INFO 
# Provides: zram 
# Required-Start: $local_fs 
# Required-Stop: $local_fs 
# Default-Start: S 
# Default-Stop: 0 1 6 
# Short-Description: Use compressed RAM as in-memory swap 
# Description: Use compressed RAM as in-memory swap 
### END INIT INFO 

# Forked by: Dale MM0HGW <dale@piratepress.org>
# rev 1: zramctl as https://askubuntu.com/questions/730749/how-to-change-zram-size
# Author: Antonio Galea <antonio.galea@gmail.com> 
# Thanks to Przemysław Tomczyk for suggesting swapoff parallelization 
# Distributed under the GPL version 3 or above, see terms at 
# https://gnu.org/licenses/gpl-3.0.txt 

FRACTION=75 
MEMORY=`perl -ne'/^MemTotal:\s+(\d+)/ && print $1*1024;' < /proc/meminfo` 
CPUS=`nproc` 
SIZE=$(( MEMORY * FRACTION / 100 / CPUS )) 
case "$1" in 
	"start") 
		param=`modinfo zram|grep num_devices|cut -f2 -d:|tr -d ' '` 
		modprobe zram $param=$CPUS 
		for n in `seq $CPUS`; do 
			i=$((n - 1)) 
			zramctl --reset /dev/zram$i
			zramctl --find --size $SIZE  /dev/zram$i 
			mkswap /dev/zram$i 
			swapon /dev/zram$i -p 100
		done 
		;; 
	"stop") 
		for n in `seq $CPUS`; do 
			i=$((n - 1)) 
			swapoff /dev/zram$i && echo "disabled disk $n of $CPUS" & 
		done 
		wait 
		sleep .5 
		modprobe -r zram 
		;; 
	*) 
		echo "Usage: `basename $0` (start | stop)" 
		exit 1 
		;; 
esac
