
png_iphone6("Scotland_1")
scatter_chart(metadata(SC_list),lwd=5,main="Scotland electoral performance '05-'16")
dev.off()
png_iphone6("Scotland_2")
scatter_chart(metadata(SC_list[7:9]),lwd=5,main="Scotland electoral performance '05-'16 referendums")
dev.off()
png_iphone6("Scotland_3")
scatter_chart(metadata(SC_list[1:6]),lwd=5,main="Scotland electoral performance '05-'16 general elections")
dev.off()
png_iphone6("UK_1")
scatter_chart(metadata(UK_list),lwd=5,main="UK electoral performance '05-'16")
dev.off()
png_iphone6("UK_2")
scatter_chart(metadata(UK_list[4:5]),lwd=5,main="UK electoral performance '05-'16 referendums")
dev.off()
png_iphone6("UK_3")
scatter_chart(metadata(UK_list[1:3]),lwd=5,main="UK electoral performance '05-'16 general elections")
dev.off()
